services:
  mysql:
    image: mysql:latest
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: teste
      MYSQL_USER: usertest
      MYSQL_PASSWORD: passtest

    volumes:
      - mysql-volume:/var/lib/mysql
    restart: always
    networks:
      - app-network

  server:
    container_name: server-container
    build: ./server
    restart: always
    ports: 
      - 3000:3000
    depends_on:
      - mysql
    env_file:
      - ./server/.env
    networks:
      - app-network
  client:
    container_name: client-container
    build: ./client
    depends_on:
      - server
    env_file:
      - ./client/.env
    volumes: 
      - client-volume:/var/www/html
    networks:
      - app-network

  nginx:
    container_name: nginx-container
    build: ./nginx
    ports:
      - 80:80
    volumes: 
      - client-volume:/var/www/html
    depends_on:
      - mysql
      - server
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-volume:
  client-volume:
